name: Build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Checkout [deepinthink-magoko/magoko-parent]
      uses: actions/checkout@v2
      with:
        repository: deepinthink-magoko/magoko-parent
        path: deepinthink-magoko/magoko-parent
    - name: Install [deepinthink-magoko/magoko-parent]
      run: |
        cd deepinthink-magoko/magoko-parent
        ./mvnw clean install -B -U
    - name: Checkout [deepinthink-magoko/magoko-config]
      uses: actions/checkout@v2
      with:
        repository: deepinthink-magoko/magoko-config
        path: deepinthink-magoko/magoko-config
    - name: Install [deepinthink-magoko/magoko-config]
      run: |
        cd deepinthink-magoko/magoko-config
        ./mvnw clean install -B -U
    - name: Checkout [deepinthink-magoko/magoko-login]
      uses: actions/checkout@v2
      with:
        repository: deepinthink-magoko/magoko-login
        path: deepinthink-magoko/magoko-login
    - name: Install [deepinthink-magoko/magoko-login]
      run: |
        cd deepinthink-magoko/magoko-login
        ./mvnw clean install -B -U
    - name: Checkout [deepinthink-magoko/magoko-pay]
      uses: actions/checkout@v2
      with:
        repository: deepinthink-magoko/magoko-pay
        path: deepinthink-magoko/magoko-pay
    - name: Install [deepinthink-magoko/magoko-pay]
      run: |
        cd deepinthink-magoko/magoko-pay
        ./mvnw clean install -B -U
    - name: Checkout [deepinthink-magoko/magoko-tinker]
      uses: actions/checkout@v2
      with:
        repository: deepinthink-magoko/magoko-tinker
        path: deepinthink-magoko/magoko-tinker
    - name: Install [deepinthink-magoko/magoko-tinker]
      run: |
        cd deepinthink-magoko/magoko-tinker
        ./mvnw clean install -B -U
    - name: Checkout [deepinthink-magoko/magoko-admin]
      uses: actions/checkout@v2
      with:
        repository: deepinthink-magoko/magoko-admin
        path: deepinthink-magoko/magoko-admin
    - name: Install [deepinthink-magoko/magoko-admin]
      run: |
        cd deepinthink-magoko/magoko-admin
        ./mvnw clean install -B -U
    - name: Checkout [deepinthink-magoko/magoko-broker]
      uses: actions/checkout@v2
      with:
        repository: deepinthink-magoko/magoko-broker
        path: deepinthink-magoko/magoko-broker
    - name: Install [deepinthink-magoko/magoko-broker]
      run: |
        cd deepinthink-magoko/magoko-broker
        ./mvnw clean install -B -U
    - name: Checkout [deepinthink-magoko/magoko-stack]
      uses: actions/checkout@v2
    - name: Checkout codingstyle
      run: |
        ./mvnw spotless:check
    - name: Build [deepinthink-magoko/magoko-stack]
      run: ./mvnw clean install -B -U
